<?php

namespace Database\Seeders;

use App\Models\Item;
use App\Models\Pricing;
use App\Models\PricingItem;
use App\Models\Zone;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PricingSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 350],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 450],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 900],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 350],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1000],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 450],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone B - Coastal Region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 450],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1100],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1000],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1200],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone A - Nairobi Region", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone B - Coastal Region", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE D - Central Highlands", "cost" => 250],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 450],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 450],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE G - Eastern Region", "cost" => 350],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1000],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone A - Nairobi Region", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone B - Coastal Region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE D - Central Highlands", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE G - Eastern Region", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone A - Nairobi Region", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone B - Coastal Region", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE D - Central Highlands", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 350],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE G - Eastern Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 700],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1000],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1200],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1200],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 800],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone A - Nairobi Region", "cost" => 900],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone B - Coastal Region", "cost" => 1300],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE D - Central Highlands", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 500],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE G - Eastern Region", "cost" => 600],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 400],
            ["item" => "Documents/Envelopes 0 - 1 kg", "min_weight" => 0, "max_weight" => 1, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 300],

            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 550],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 650],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1100],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 550],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1200],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 650],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone B - Coastal Region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 650],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1300],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1200],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1400],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone A - Nairobi Region", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone B - Coastal Region", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE D - Central Highlands", "cost" => 450],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 650],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 650],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE G - Eastern Region", "cost" => 550],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1200],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone A - Nairobi Region", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone B - Coastal Region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE D - Central Highlands", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE G - Eastern Region", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone A - Nairobi Region", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone B - Coastal Region", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE D - Central Highlands", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 550],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE G - Eastern Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 900],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1200],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1400],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1400],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1000],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1100],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone B - Coastal Region", "cost" => 1500],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 700],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE G - Eastern Region", "cost" => 800],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 600],
            ["item" => "Small Parcels/package 1-5kg", "min_weight" => 1, "max_weight" => 5, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 500],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 700],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 800],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1250],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 700],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1350],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 800],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 800],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1450],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1350],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1550],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone A - Nairobi Region", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone B - Coastal Region", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE D - Central Highlands", "cost" => 600],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 800],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 800],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE G - Eastern Region", "cost" => 700],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1350],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone A - Nairobi Region", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone B - Coastal Region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE D - Central Highlands", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE G - Eastern Region", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone A - Nairobi Region", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone B - Coastal Region", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE D - Central Highlands", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 700],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE G - Eastern Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1050],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1350],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1550],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1550],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1150],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1250],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone B - Coastal Region", "cost" => 1650],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE D - Central Highlands", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 850],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE G - Eastern Region", "cost" => 950],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 750],
            ["item" => "Medium (A) Parcels /package 5-15kg", "min_weight" => 5, "max_weight" => 15, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 650],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 750],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 850],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1300],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 750],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1400],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 850],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 850],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1500],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1400],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1600],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone A - Nairobi Region", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone B - Coastal Region", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE D - Central Highlands", "cost" => 650],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 850],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 850],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE G - Eastern Region", "cost" => 750],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1400],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone A - Nairobi Region", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone B - Coastal Region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE G - Eastern Region", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone A - Nairobi Region", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone B - Coastal Region", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 750],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1100],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1400],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1600],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1600],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1200],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1300],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone B - Coastal Region", "cost" => 1700],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 900],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1000],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Medium (B) Parcels/package 15-40kg", "min_weight" => 15, "max_weight" => 40, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 700],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 850],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 950],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone A - Nairobi Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1400],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 850],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone B - Coastal Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1500],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 950],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 950],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1600],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1500],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "Zone C - Nyanza and Western region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1700],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone A - Nairobi Region", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone B - Coastal Region", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE D - Central Highlands", "cost" => 750],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 950],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 950],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE G - Eastern Region", "cost" => 850],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE D - Central Highlands", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1500],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone B - Coastal Region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE D - Central Highlands", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE E - Rift Valley South", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone A - Nairobi Region", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone B - Coastal Region", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE D - Central Highlands", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 850],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE F - Rift Valley North", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1200],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE G - Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 1500],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone B - Coastal Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 1700],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1700],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 1300],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE H - North Eastern Region", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 2000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone A - Nairobi Region", "cost" => 1400],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone B - Coastal Region", "cost" => 1800],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "Zone C - Nyanza and Western region", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE D - Central Highlands", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE E - Rift Valley South", "cost" => 1000],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE F - Rift Valley North", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE G - Eastern Region", "cost" => 1100],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE H - North Eastern Region", "cost" => 900],
            ["item" => "Large Parcels/package 40 kg-75kg", "min_weight" => 40, "max_weight" => 75, "source_zone" => "ZONE I - Northern Kenya", "destination_zone" => "ZONE I - Northern Kenya", "cost" => 800]
        ];

        foreach ($categories as $row) {
            // 1. Get item_id
            $item = $row['item'] ?? null;

            if (!$item) {
                continue;
            }

            //Get Item Id
            $item = Item::where('name', $item)->first();
            $itemId = $item->id;

            // 2. Get zone IDs (trim to avoid spacing issues)
            $sourceZone = Zone::where('name', $row['source_zone'])->first();
            $destinationZone = Zone::where('name', $row['destination_zone'])->first();

            $sourceZoneId = $sourceZone->id;
            $destinationZoneId = $destinationZone->id;


            if (!$sourceZoneId || !$destinationZoneId) {
                continue; // or log missing zones
            }

            // 3. Create or fetch pricing (avoid duplicates)

            $pricing = Pricing::updateOrCreate(
                [ // search
                    'item_id' => $itemId,
                    'min_weight' => $row['min_weight'],
                    'max_weight' => $row['max_weight'],
                ],
                [ // values to update/create
                    'item_id' => $itemId, // optional but safe
                ]
            );

            // 4. Insert pricing_items
            PricingItem::updateOrCreate(
                [
                    'pricing_id' => $pricing->id,
                    'source_zone_id' => $sourceZoneId,
                    'destination_zone_id' => $destinationZoneId,
                ],
                [
                    'cost' => $row['cost'],
                ]
            );
        }
    }
}
